[package]
name = "rsmgp-example"
version = "0.1.0"
authors = ["Marko Budiselic <marko.budiselic@memgraph.com>"]
edition = "2018"

[dependencies]
c_str_macro = "1.0.2"
rsmgp-sys = "^0.1.0"

[lib]
name = "rust_example"
crate-type = ["cdylib"]
