memgraph:
  image:
    repository: memgraph/memgraph
    tag: 2.18.1 # TODO(gitbuda): The tag here is not appreciated.
    pullPolicy: IfNotPresent
  env:
    MEMGRAPH_ENTERPRISE_LICENSE: "<your-license>"
    MEMGRAPH_ORGANIZATION_NAME: "<your-organization-name>"
  probes:
    startup:
      failureThreshold: 30
      periodSeconds: 10
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 5
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 10
  data:
    volumeClaim:
      storagePVCClassName: ""
      storagePVC: true
      storagePVCSize: "1Gi"
      logPVCClassName: ""
      logPVC: true
      logPVCSize: "256Mi"
  coordinators:
    volumeClaim:
      storagePVCClassName: ""
      storagePVC: true
      storagePVCSize: "1Gi"
      logPVCClassName: ""
      logPVC: true
      logPVCSize: "256Mi"
  affinity:
    enabled: false

data:
- id: "0"
  boltPort: 7687
  managementPort: 10000
  replicationPort: 20000
  args:
  - "--management-port=10000"
  - "--bolt-port=7687"
  - "--also-log-to-stderr"
  - "--log-level=TRACE"
  - "--log-file=/var/log/memgraph/memgraph.log"
  - "--telemetry-enabled=False"

- id: "1"
  boltPort: 7687
  managementPort: 10000
  replicationPort: 20000
  args:
  - "--management-port=10000"
  - "--bolt-port=7687"
  - "--also-log-to-stderr"
  - "--log-level=TRACE"
  - "--log-file=/var/log/memgraph/memgraph.log"
  - "--telemetry-enabled=False"

coordinators:
- id: "1"
  boltPort: 7687
  managementPort: 10000
  coordinatorPort: 12000
  args:
  - "--coordinator-id=1"
  - "--coordinator-port=12000"
  - "--management-port=10000"
  - "--bolt-port=7687"
  - "--also-log-to-stderr"
  - "--log-level=TRACE"
  - "--coordinator-hostname=memgraph-coordinator-1.default.svc.cluster.local"
  - "--log-file=/var/log/memgraph/memgraph.log"
  - "--nuraft-log-file=/var/log/memgraph/memgraph.log"
  - "--telemetry-enabled=False"

- id: "2"
  boltPort: 7687
  managementPort: 10000
  coordinatorPort: 12000
  args:
  - "--coordinator-id=2"
  - "--coordinator-port=12000"
  - "--management-port=10000"
  - "--bolt-port=7687"
  - "--also-log-to-stderr"
  - "--log-level=TRACE"
  - "--coordinator-hostname=memgraph-coordinator-2.default.svc.cluster.local"
  - "--log-file=/var/log/memgraph/memgraph.log"
  - "--nuraft-log-file=/var/log/memgraph/memgraph.log"
  - "--telemetry-enabled=False"

- id: "3"
  boltPort: 7687
  managementPort: 10000
  coordinatorPort: 12000
  args:
  - "--coordinator-id=3"
  - "--coordinator-port=12000"
  - "--management-port=10000"
  - "--bolt-port=7687"
  - "--also-log-to-stderr"
  - "--log-level=TRACE"
  - "--coordinator-hostname=memgraph-coordinator-3.default.svc.cluster.local"
  - "--log-file=/var/log/memgraph/memgraph.log"
  - "--nuraft-log-file=/var/log/memgraph/memgraph.log"
  - "--telemetry-enabled=False"
