#!/usr/bin/env python3

import os
import re
import subprocess
import shutil
import glob
import fnmatch
import multiprocessing as mp
import argparse
import logging as log
from enum import Enum

WORK_DIRECTORY = os.getcwd()
MAGE_BUILD_DIRECTORY = f"{WORK_DIRECTORY}/dist"
LICENCE_DIRECTORY = f"{WORK_DIRECTORY}/licences"
CPP_DIRECTORY = f"{WORK_DIRECTORY}/cpp"
PY_DIRECTORY = f"{WORK_DIRECTORY}/python"
RS_DIRECTORY = f"{WORK_DIRECTORY}/rust"
CPP_BUILD_DIRECTORY = f"{CPP_DIRECTORY}/build"
MG_CONF_DEFAULT_PATH = f"/etc/memgraph/memgraph.conf"
MG_CONF_QUERY_MODULES_FLAG = "--query-modules-directory"
MAGE_GPU_BUILD = "MAGE_CUGRAPH_ENABLE=ON"

log.basicConfig(level=log.INFO)

HELP_MESSAGE = """\
    For usage info run: python3 setup -h
    """

class BuildType(Enum):
    DEBUG = "Debug"
    RELEASE = "Release"

    def __str__(self):
        return self.value


def get_arguments():
    parser = argparse.ArgumentParser(
        description="MAGE setup script",
    )
    subparsers = parser.add_subparsers(help="sub-command help", dest="action")

    build_args_parser = argparse.ArgumentParser(description="Build arguments", add_help=False)
    build_args_parser.add_argument(
        "-p", "--path", help="Path to query modules directory", required=False
    )
    build_args_parser.add_argument(
        "--type", help="Build type", type=BuildType, choices=list(BuildType), required=False
    )
    build_args_parser.add_argument(
        "--gpu", help="GPU Algorithms", action='store_true'
    )
    build_args_parser.add_argument(
        "--cpp-build-flags", nargs="+", help="CMake flags for the cpp part (without -D)", required=False
    )
    build_parser = subparsers.add_parser("build", help="Build memgraph-mage", parents=[build_args_parser])

    query_modules_parser = subparsers.add_parser(
        "modules_storage", help="Add path of mage/dist to memgraph.conf "
    )
    query_modules_parser.add_argument(
        "--conf_path",
        "-cp",
        help="Path to Memgraph configuration file",
        required=False,
        default=MG_CONF_DEFAULT_PATH,
    )
    query_modules_parser.add_argument(
        "--path",
        "-p",
        help="Path to new query_modules storage",
        required=False,
        default=MAGE_BUILD_DIRECTORY,
    )

    subparsers.add_parser("all", help="Set up memgraph-mage for usage", parents=[build_args_parser])

    return parser.parse_args()


#################################################
#                Copy Utility                   #
#################################################


def copytree(src, dst, ignore_patterns=[]):
    def _check_ignore(x):
        return any([bool(fnmatch.fnmatch(x, pattern)) for pattern in ignore_patterns])

    def _copytree(rel_path=""):
        curr_dir = os.path.join(src, rel_path)
        for item in os.listdir(curr_dir):
            if _check_ignore(item):
                continue

            abs_item = os.path.join(curr_dir, item)
            rel_item = os.path.join(rel_path, item)

            if os.path.isdir(abs_item):
                _copytree(rel_item)
                continue

            destination = os.path.dirname(
                os.path.join(dst, rel_item)
            )  # Joining the tree-based name

            os.makedirs(destination, exist_ok=True)
            shutil.copy2(abs_item, destination)

    _copytree()


def build(args):
    shutil.rmtree(MAGE_BUILD_DIRECTORY, ignore_errors=True)
    os.makedirs(MAGE_BUILD_DIRECTORY, exist_ok=True)
    copytree(LICENCE_DIRECTORY, MAGE_BUILD_DIRECTORY)

    #################################################
    #              Load C++ modules                 #
    #################################################

    # Make build directory
    os.makedirs(CPP_BUILD_DIRECTORY, exist_ok=True)

    # Start CMake building
    os.chdir(CPP_BUILD_DIRECTORY)
    subprocess.run(["ls", "-l"])
    cmake_args = [".."]
    if args.gpu:
        cmake_args.append(f"-D{MAGE_GPU_BUILD}")
    if args.cpp_build_flags is not None:
        cmake_args += [f"-D{flag}" for flag in args.cpp_build_flags]
    subprocess.run(["cmake"] + cmake_args)
    core_count = mp.cpu_count()
    subprocess.run(["make", f"-j{core_count}"])

    # Transfer files to the query modules directory. The transfer is tricky
    # because e.g. cugraph generates a bunch of stuff, a new contributor might
    # get confused with the amount of stuff that ends up in the dist.
    # NOTE: Cugraph only compiles to a SHARED library.
    # NOTE: This is dependent on the cpp/cmake/cugraph ExternalProject_Add (on
    # the INSTALL_DIR).
    all_so = set(glob.glob("**/*.so", recursive=True))
    for file in all_so:
        shutil.copy2(file, MAGE_BUILD_DIRECTORY)

    #################################################
    #             Load Python modules               #
    #################################################

    os.chdir(PY_DIRECTORY)
    ignore_list = [
        "tests",
        "requirements.txt",
        "pytest.ini",
        "htmlcov",
        "__pycache__",
        ".*",
    ]

    # Copy python repository tree inside dist folder
    copytree(PY_DIRECTORY, MAGE_BUILD_DIRECTORY, ignore_list)
    os.environ["PYTHONPATH"] = PY_DIRECTORY

    #################################################
    #              Load Rust modules                #
    #################################################

    os.chdir(RS_DIRECTORY)
    for project in filter(
        lambda f: os.path.isdir(f) and f != "rsmgp-sys", os.listdir(RS_DIRECTORY)
    ):
        project_dir = os.path.join(RS_DIRECTORY, project)
        os.chdir(project_dir)
        rs_build_mode = "release"
        if args.type is not None:
            if args.type == BuildType.DEBUG: rs_build_mode = "debug"
            if args.type == BuildType.RELEASE: rs_build_mode = "release"
        rs_build_flags = ["--release"]
        if args.type is not None and args.type == BuildType.DEBUG:
            rs_build_flags = []
        subprocess.run(["cargo", "build"] + rs_build_flags)

        release_dir = os.path.join(project_dir, "target", "%s" % rs_build_mode)
        os.chdir(release_dir)
        modules = glob.glob("*.so")
        assert len(modules) == 1, f"Bad rust/{project} lib."

        module = modules[0]
        src_file = os.path.join(release_dir, module)
        module = module.lstrip("lib") if module.startswith("lib") else module
        dst_file = os.path.join(MAGE_BUILD_DIRECTORY, module)
        shutil.copy2(src_file, dst_file)


def run_build_action(args):
    log.log(level=log.INFO, msg="Starting building of source code...")
    build(args)
    log.log(level=log.INFO, msg="Building done.")

    if args.path is None:
        return

    log.log(
        level=log.INFO,
        msg="Copying build files from folder {src} to {dst} folder.".format(
            src=MAGE_BUILD_DIRECTORY, dst=args.path
        ),
    )

    copytree(MAGE_BUILD_DIRECTORY, args.path)
    log.log(level=log.INFO, msg="Copying done!")


def change_file_lines(file_path: str, pattern: str, substitution: str):
    with open(file_path, "r") as file:
        data = file.readlines()

    data = [re.sub(pattern, substitution, line) for line in data]

    with open(file_path, "w") as file:
        file.writelines(data)


def run_modules_storage_setup_action(
    modules_storage_path=MAGE_BUILD_DIRECTORY, mg_conf_path=MG_CONF_DEFAULT_PATH
):
    if not os.path.isfile(mg_conf_path):
        log.log(
            level=log.INFO,
            msg="Configuration path does not exists: {path}. Check out whether you have installed Memgraph!".format(
                path=mg_conf_path
            ),
        )
        return

    log.log(
        level=log.INFO,
        msg="--query-modules-dir flag in {memgraph_conf} will be set to {path}".format(
            path=modules_storage_path, memgraph_conf=mg_conf_path
        ),
    )

    change_file_lines(
        mg_conf_path,
        r".*({query_modules_flag}).*".format(
            query_modules_flag=MG_CONF_QUERY_MODULES_FLAG
        ),
        r"\1={path}".format(path=modules_storage_path),
    )

    log.log(
        level=log.INFO,
        msg="--query-modules-dir flag set to {path}".format(path=modules_storage_path),
    )


def main():
    args = get_arguments()

    if not hasattr(args, "action"):
        log.log(level=log.INFO, msg=HELP_MESSAGE)
        return

    if args.action == "all":
        run_modules_storage_setup_action()
        run_build_action(args)
        return

    if args.action == "build":
        run_build_action(args)
        return

    if args.action == "modules_storage":
        run_modules_storage_setup_action(args.path, args.conf_path)
        return


if __name__ == "__main__":
    main()
