apiVersion: kubeadm.k8s.io/v1beta3 # To figure out run `kubeadm config print init-defaults | head`.
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 100.99.96.28
discovery:
  bootstrapToken:
    token: <BOOTSTRAP_TOKEN>
    apiServerEndpoint: 100.94.19.81:6443
    caCertHashes:
    - <CA_CERT_HASH>
