[package]
name = "mage"
version = "0.1.0"
authors = ["Marko Budiselic <marko.budiselic@memgraph.com>"]
edition = "2018"

[dependencies]
c_str_macro = "1.0.2"
snafu = "0.6.10"

[build-dependencies]
bindgen = "0.57.0"

[lib]
name = "rust_example_query_module"
crate-type = ["cdylib"]
