#!/bin/sh
set -e

case "$1" in
    configure)
        # install requirements as user memgraph
        su - memgraph -c "pip install --no-cache-dir -r /usr/lib/memgraph/mage-requirements.txt --break-system-packages"
        systemctl restart memgraph.service
    ;;
esac

exit 0
