[package]
name = "rsmgp-module-template"
version = "0.1.0"
edition = "2018"

[dependencies]
c_str_macro = "1.0.2"
rsmgp-sys = { path = "../rsmgp-sys" }

[lib]
name = "rust_module_template"
crate-type = ["cdylib"]
