name: Publish Docker image
on:
  push:
    tags:
      - v*.*.*
      - v*.*

jobs:
  build_with_tag:
    name: Build Docker image with tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}
          with:
            semver_only: true

      - name: Get commit tag
        id: get-commit-tag
        run: |
           export VERSION=${GITHUB_REF#refs/tags/}
           echo "::set-output name=VERSION_TAG::${VERSION:1}"
           echo ${{ steps.get-latest-tag.outputs.tag }}


      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push production image to Docker Hub
        id: docker-build-prod
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: memgraph/memgraph-mage:latest, memgraph/memgraph-mage:${{ steps.get-commit-tag.outputs.VERSION_TAG }}
          target: prod
          file: ./Dockerfile

      - name: Push development image to Docker Hub
        id: docker-build-dev
        uses: docker/build-push-action@v2
        with:
            push: false
            tags: memgraph/memgraph-mage:${{ steps.get-commit-tag.outputs.VERSION_TAG }}-dev
            target: dev
            file: ./Dockerfile

      - name: Get image digest
        run: echo ${{ steps.docker-build-prod.outputs.metadata }}
