name: Publish Docker image
on:
  push:
    branches:
      - T075-MAGE-add-releases
    tags:
      - v*.*.*

jobs:
  build_with_tag:
    name: Build Docker image with tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get commit tag
        id: get-commit-tag
        run: |
           echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"
           echo ::set-output name=VERSION_2::${GITHUB_REF#refs/tags/}
      - name: Get version
        run: echo "Version is ${{ steps.get-commit-tag.outputs.VERSION }}"
      - name: Get version 2
        run: echo "Version is ${{ steps.get-commit-tag.outputs.VERSION_2 }}"
