name: Publish Docker image
on:
  push:
    tags:
      - v*.*.*
      - v*.*

jobs:
  build_with_tag:
    name: Build Docker image with tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get latest tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: memgraph/mage
          releases-only: false
          prefix: 'v'
        id: get-latest-tag

      - run: echo "MAGE is at version ${{ steps.get-latest-tag.outputs.tag }}"

      - name: Get commit tag
        id: get-commit-tag
        run: |
           export VERSION=${GITHUB_REF#refs/tags/}
           echo "::set-output name=VERSION_TAG::${VERSION:1}"
           echo "::set-output name=VERSION::${VERSION}"

      - name: Get version
        run: echo "Version is ${{ steps.get-commit-tag.outputs.VERSION }}"

      - name: Set production tag
        id: get-prod-tags
        run: |
            if [ "${{ steps.get-commit-tag.outputs.VERSION }}" == "${{ steps.get-latest-tag.outputs.tag }}" ]
            then
              echo "::set-output name=PROD_TAGS::memgraph/memgraph-mage:${{ steps.get-commit-tag.outputs.VERSION_TAG }},memgraph/memgraph-mage:latest"
            else
               echo "::set-output name=PROD_TAGS::memgraph/memgraph-mage:${{ steps.get-commit-tag.outputs.VERSION_TAG }}"
            fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push production image to Docker Hub
        id: docker-build-prod
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ steps.get-prod-tag.outputs.PROD_TAGS }}
          target: prod
          file: ./Dockerfile

      - name: Push development image to Docker Hub
        id: docker-build-dev
        uses: docker/build-push-action@v2
        with:
            push: false
            tags: memgraph/memgraph-mage:${{ steps.get-commit-tag.outputs.VERSION_TAG }}-dev
            target: dev
            file: ./Dockerfile
