name: Reusable Vulnerability Scan

on:
  workflow_call:
    inputs:
      arch: 
        type: string
        description: "Image architecture (amd64|arm64)"
        required: true
      image_url:
        type: string
        description: "URL of docker image to scan"
        required: true
      image_type:
        type: string
        description: "Image type (memgraph|mage)"
        required: true
      run_trivy:
        type: boolean
        description: "Scan with Trivy"
        default: true
      run_grype:
        type: boolean
        description: "Scan with Grype"
        default: true
      run_cbt:
        type: boolean
        description: "Scan with CVE-bin-tool"
        default: true
      send_slack_message:
        type: boolean
        description: "Send a Slack message"
        default: true

jobs:
  scan-image:
    name: Scan Docker Image for Vulnerabilities (${{ inputs.image_type }}, ${{ inputs.arch }})
    runs-on: ${{ (inputs.arch == 'arm64') && fromJSON('["self-hosted", "Linux", "Docker", "ARM64", "Ubuntu24.04"]') || fromJSON('["self-hosted", "Linux", "Docker", "X64", "Ubuntu24.04"]') }}
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Scan Directory
        run: |
          CVE_DIR="$(pwd)/cve-scan"
          mkdir -p "$CVE_DIR"
          echo "CVE_DIR=$CVE_DIR" >> $GITHUB_ENV  

      - name: Create Python Environment
        run: |
          python3 -m venv "${{ env.CVE_DIR }}/env" 
          source "${{ env.CVE_DIR }}/env/bin/activate"
          pip install requests tqdm
          
      - name: Install Trivy
        if: ${{ inputs.run_trivy }}
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b "${{ env.CVE_DIR }}/trivy" latest

      - name: Install Grype
        if: ${{ inputs.run_grype }}
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b "${{ env.CVE_DIR }}/grype"
          "${{ env.CVE_DIR }}/grype/grype" db update
          
      - name: Install cve-bin-tool
        if: ${{ inputs.run_cbt }}
        run: |
          source "${{ env.CVE_DIR }}/env/bin/activate"
          pip install cve-bin-tool==3.4

      - name: Download Docker Image
        run: |
          curl -L "${{ inputs.image_url }}" -o "${{ env.CVE_DIR }}/image.tar.gz"

      - name: Load into Docker
        run: |
          output="$(docker load -i '${{ env.CVE_DIR }}/image.tar.gz')"

          # grab each repo:tag, drop the ":latest" one, pick the first real tag
          image_tag=$(echo "$output" \
            | awk -F': ' '/Loaded image:/ {print $2}' \
            | grep -v ':latest$' \
            | head -n1)

          echo "IMAGE_TAG=$image_tag" >> $GITHUB_ENV

      - name: Decompress Image
        run: |
          # this is needed because grype annot scan the compressed image, however trivy can
          gunzip "${{ env.CVE_DIR }}/image.tar.gz"

      - name: Extract Container Root Filesystem
        if: ${{ inputs.run_cbt }}
        run: |
          ./scripts/extract-image-filesystem.sh "${{ env.IMAGE_TAG }}" "${{ env.CVE_DIR }}/rootfs"

      - name: Scan with Trivy
        if: ${{ inputs.run_trivy }}
        run: |
          "${{ env.CVE_DIR }}/trivy/trivy" image --scanners vuln --input "${{ env.CVE_DIR }}/image.tar" > "${{ env.CVE_DIR }}/trivy-summary.txt"
          "${{ env.CVE_DIR }}/trivy/trivy" image --scanners vuln --input "${{ env.CVE_DIR }}/image.tar" -f json > "${{ env.CVE_DIR }}/trivy-summary.json"
        
      - name: Upload Trivy Report Summary Artifact
        if: ${{ inputs.run_trivy }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image_type }}-${{ inputs.arch }}-trivy-summary
          path: "${{ env.CVE_DIR }}/trivy-summary.txt"        

      - name: Scan with Grype
        if: ${{ inputs.run_grype }}
        run: |
          "${{ env.CVE_DIR }}/grype/grype" "docker-archive:${{ env.CVE_DIR }}/image.tar" > "${{ env.CVE_DIR }}/grype-summary.txt"
          "${{ env.CVE_DIR }}/grype/grype" "docker-archive:${{ env.CVE_DIR }}/image.tar" -o json > "${{ env.CVE_DIR }}/grype-summary.json"

      - name: Upload Grype Report Summary Artifact
        if: ${{ inputs.run_grype }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image_type }}-${{ inputs.arch }}-grype-summary
          path: "${{ env.CVE_DIR }}/grype-summary.txt"
          
      - name: Launch Docker Container
        if: ${{ inputs.run_cbt }}
        run: |
          docker run --rm -d --name memgraph "${{ env.IMAGE_TAG }}" --telemetry-enabled=False
      
      # - name: Update CVE Database
      #   if: ${{ inputs.run_cbt }}
      #   id: update-cve-db
      #   continue-on-error: true  # this can be flaky
      #   run: |
      #     source "${{ env.CVE_DIR }}/env/bin/activate"
      #     python3 scripts/update_cve_db.py

      - name: Download CVE Database
        if: ${{ inputs.run_cbt }}
        run: |
          curl -L https://s3.eu-west-1.amazonaws.com/deps.memgraph.io/CVE-database/cve-bin-tool-cve.db.tar.gz -o "${{ env.CVE_DIR }}/cve-bin-tool-cve.db.tar.gz"

      - name: Extract CVE Database
        if: ${{ inputs.run_cbt }}
        run: |
          tar -xzf "${{ env.CVE_DIR }}/cve-bin-tool-cve.db.tar.gz" -C "${{ env.CVE_DIR }}/cve.db"
          mv -v "${{ env.CVE_DIR }}/cve.db/cve.db" "$HOME/.cache/cve-bin-tool/cve.db"

      - name: Scan /usr/lib/memgraph
        if: ${{ inputs.run_cbt  }}
        run: |
          source "${{ env.CVE_DIR }}/env/bin/activate"
          python3 scripts/scan_memgraph.py "${{ env.CVE_DIR }}/rootfs" "$(nproc)"

      - name: Scan Languages
        if: ${{ inputs.run_cbt }}
        run: |
          source "${{ env.CVE_DIR }}/env/bin/activate"
          python3 scripts/scan_languages.py "${{ env.CVE_DIR }}/rootfs"

      - name: Scan APT Packages
        if: ${{ inputs.run_cbt }}
        run: |
          source "${{ env.CVE_DIR }}/env/bin/activate"
          python3 scripts/scan_apt.py "${{ env.IMAGE_TAG }}"

      - name: Upload cve-bin-tool Binary Scan Artifact
        if: ${{ inputs.run_cbt }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image_type }}-${{ inputs.arch }}-cve-bin-tool-memgraph-summary
          path: "${{ env.CVE_DIR }}/cve-bin-tool-memgraph-summary.json"

      - name: Upload cve-bin-tool Language Scan Artifact
        if: ${{ inputs.run_cbt  }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image_type }}-${{ inputs.arch }}-cve-bin-tool-language-summary
          path: "${{ env.CVE_DIR }}/cve-bin-tool-lang-summary.json"
          
      - name: Upload cve-bin-tool APT Package Scan Artifact
        if: ${{ inputs.run_cbt }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image_type }}-${{ inputs.arch }}-cve-bin-tool-apt-summary
          path: "${{ env.CVE_DIR }}/cve-bin-tool-apt-summary.json"

      - name: Send Slack Message
        if: ${{ inputs.send_slack_message && always() }}
        id: slack-message
        env:
          INFRA_WEBHOOK_URL: ${{ secrets.INFRA_WEBHOOK_URL }}
        run: |
          # Check if any summary files exist
          files=(
            trivy-summary.json
            grype-summary.json
            cve-bin-tool-memgraph-summary.json
            cve-bin-tool-lang-summary.json
            cve-bin-tool-apt-summary.json
          )
          
          summary_files_exist=false
          for file in "${files[@]}"; do
            if [ -f "${{ env.CVE_DIR }}/$file" ]; then
              summary_files_exist=true
              break
            fi
          done

          if [ "$summary_files_exist" = true ]; then
            source "${{ env.CVE_DIR }}/env/bin/activate"
            python3 scripts/cve_message.py "${{ inputs.arch }}" "${{ inputs.image_type }}"
          else
            echo "No summary files found. Skipping Slack message"
          fi

      - name: Upload Full CVE List artifact
        if: ${{ steps.slack-message.outputs.success }}
        uses: actions/upload-artifact@v4
        with:
          name: full-cve-list-artifact
          path: "${{ env.CVE_DIR }}/full-cve-list.txt"

      - name: Cleanup
        if: always()
        run: |
          rm -rf ${{ env.CVE_DIR }}
          rm -v "$HOME/.cache/cve-bin-tool/cve.db" || true
          docker stop memgraph || true
          docker wait memgraph || true
          docker rmi ${{ env.IMAGE_TAG }} || true
