name: "Smoke Testing"


on:
  workflow_dispatch:
    inputs:
      next_version:
        type: string
        required: false
        description: "Version (x.y.z), daily build date (YYYYMMDD), or URL to Docker image: Default - latest daily build"
      last_version:
        type: string
        required: false
        description: "Version (x.y.z), daily build date (YYYYMMDD), or URL to Docker image: Default - latest release"
      arch:
        type: choice
        default: "amd64"
        options:
        - "arm64"
        - "amd64"
        required: false
        description: "Architecture to build the image for (amd64/arm64)"
      malloc:
        type: boolean
        default: false
        description: "Test malloc build"

jobs:
  smoke-release-tests-setup:
    runs-on: ["ubuntu-latest"]