name: "Smoke Testing"


on:
  workflow_dispatch:
    inputs:
      next_version:
        type: string
        required: false
        description: "Version (x.y.z), daily build date (YYYYMMDD), or URL to Docker image: Default - latest daily build"
      last_version:
        type: string
        required: false
        description: "Version (x.y.z), daily build date (YYYYMMDD), or URL to Docker image: Default - latest release"
      arch:
        type: choice
        default: "amd64"
        options:
        - "all"
        - "arm64"
        - "amd64"
        required: false
        description: "Architecture to build the image for (amd64/arm64)"
      malloc:
        type: boolean
        default: false
        description: "Test malloc build"

jobs:
  smoke-release-tests-setup:
    runs-on: ["ubuntu-latest"]
    env:
      GH_CONTEXT: ${{ toJson(github) }}
      GH_CONTEXT_FILE_NAME: github_context.json
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Dump GitHub context
        run: echo "$GH_CONTEXT" >> "$GH_CONTEXT_FILE_NAME"
      - name: Set up test execution
        id: setup
        run: ./smoke-release-testing/workflow-setup.py "$GH_CONTEXT_FILE_NAME" 
