name: Test Docker Image
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:
    inputs:
      arch: 
        type: string
        description: "Image architecture (amd64|arm64)"
        required: true
      image:
        type: string
        description: "URL or repo:tag of docker image to scan"
        required: true

jobs:
  test_mage_image:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Manual MAGE Image Test
    uses: ./.github/workflows/reusable_test.yml
    with:
      arch: ${{ inputs.arch }}
      mage_image: ${{ inputs.image }}
    secrets: inherit

  test_mage_image_push:
    if: ${{ github.event_name == 'push' }}
    name: Manual MAGE Image Test
    uses: ./.github/workflows/reusable_test.yml
    with:
      arch: "arm64"
      mage_image: "memgraph/memgraph-mage:3.3.0"
    secrets: inherit
    


